ec-th2012-c/ec-th2012-c/Models/PRODUCTS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ec_th2012_c.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.BILL2C_DETAIL = new HashSet<BILL2C_DETAIL>();
            this.CARTS = new HashSet<CARTS>();
            this.COMMENT = new HashSet<COMMENT>();
            this.CONTRACT_BUYSIDE = new HashSet<CONTRACT_BUYSIDE>();
            this.CONTRACT_SELLSIDE = new HashSet<CONTRACT_SELLSIDE>();
            this.PRODUCT_INFO = new HashSet<PRODUCT_INFO>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMG { get; set; }
        public Nullable<int> VIEWNUMBER { get; set; }
        public Nullable<System.DateTime> TIMEUPDATE { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> CATE_DEP_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL2C_DETAIL> BILL2C_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTS> CARTS { get; set; }
        public virtual CATE_DEP CATE_DEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACT_BUYSIDE> CONTRACT_BUYSIDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACT_SELLSIDE> CONTRACT_SELLSIDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_INFO> PRODUCT_INFO { get; set; }
    }
}

ec-th2012-c/ec-th2012-c/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ec_th2012_c.DAO;
using ec_th2012_c.Models;
using PagedList;
using PagedList.Mvc;

namespace ec_th2012_c.Controllers
{
    public class ProductController : Controller
    {
        int pageSize = 8;
        public ActionResult showCategory(int depID, int? cateID, int? page)
        {
            try
            {
                ViewBag.depID = depID;
                ViewBag.cateID = (cateID ?? -1);
                int pageNumber = (page ?? 1);

                IList<PRODUCTS> ps;

                //return View();
                if (ViewBag.cateID < 0)
                {
                    ViewBag.Title = new DepartmentDAO().getById(depID).NAME;
                    ps = new ProductDAO().getByCategory(depID);
                }
                else
                {
                    ViewBag.Title = new CategoryDAO().getById(cateID.GetValueOrDefault()).NAME;
                    ps = new ProductDAO().getByCategory(depID, cateID.GetValueOrDefault());
                }
                return View(ps.ToPagedList(pageNumber, pageSize));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult showProduct(int proID, int? page)
        {
            try
            {
                PRODUCTS p = new ProductDAO().getById(proID);
                IList<PRODUCTS> ps = new ProductDAO().getSameCategoryItemsById(proID);
                int pageNumber = (page ?? 1);

                ViewBag.SameCategoryItems = ps.ToPagedList(pageNumber, pageSize);
                ViewBag.proID = proID;
                ViewBag.Title = p.NAME;
                ViewBag.categories = new CategoryDAO().getByDepartmentId(p.CATE_DEP.DEPARTMENT_ID);
                new ProductDAO().updateViewNum(proID);
                return View(p);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        public ActionResult Search(string keyword, int? page)
        {
            try
            {
                IList<PRODUCTS> ps;
                @ViewBag.Title = "Search result";
                //if(keyword == null || keyword.Equals(string.Empty))

                ps = new ProductDAO().getByName(keyword);
                int pageNumber = (page ?? 1);

                return View(ps.ToPagedList(pageNumber, pageSize));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult AdvancedSearch(string name, int department, int category, long? MinPrice, long? MaxPrice, int? page)
        {
            try
            {
                @ViewBag.Title = "Search result";
                @ViewBag.name = name;
                @ViewBag.department = department;
                @ViewBag.category = category;
                @ViewBag.MinPrice = (MinPrice ?? 0);
                @ViewBag.MaxPrice = (MaxPrice ?? 0);
                IList<PRODUCTS> ps = new ProductDAO().getByMultiValues(name, department, category, (MinPrice ?? 0), (MaxPrice ?? 0));
                //IList<PRODUCTS> ps = new ProductDAO().testLambdaExpression(Int32.Parse(department));
                int pageNumber = (page ?? 1);

                return View(ps.ToPagedList(pageNumber, pageSize));
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize(Roles="")]
        [HttpGet]
        public ActionResult Comment()
        {
            try
            {
                COMMENT c = new COMMENT() { PRODUCTID = int.Parse(Request["pID"]), USERID = User.Identity.GetUserId(), MESSAGE = Request["message"], DATACREATE = DateTime.Now };
                new CommentDAO().addComment(c);
                //List<COMMENT> lst = new CommentDAO().getAllSortByTime(c.PRODUCTID).ToList();
                string name = new UserDAO().getAspNetUserbyUserID(c.USERID).UserName;
                //string json = JsonConvert.SerializeObject(c);
                var json = new { UserName = name, DATECREATE = c.DATACREATE.ToString(), MESSAGE = c.MESSAGE};
                return Json(json, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ec-th2012-c/ec-th2012-c/Views/Product/AdvancedSearch.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<ec_th2012_c.Models.PRODUCTS>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="wrap">

    <div class="content">

        @Html.Partial("_Layout_Categories")
        @Html.Partial("_Layout_Search")
        <div class="content-grids">
            @{int size = Model.Count(); int i = 0;}
            @while (i < size)
            {
                <div class="section group">
                    @for (int g = 0; g < 4; g++)
                    {
                        if (i >= size)
                        {
                            break;
                        }
                        <div class="grid_1_of_4 images_1_of_4 products-info">
                            <a href="/Product/showProduct?proID=@Model.ElementAt(i).ID">
                                <img src="@Model.ElementAt(i).IMG" title="@Model.ElementAt(i).NAME">
                            </a>
                            <a href="/Product/showProduct?proID=@Model.ElementAt(i).ID">@Model.ElementAt(i).NAME</a>
                            @if (Model.ElementAt(i).QUANTITY > 0)
                            {
                                if (Model.ElementAt(i).CATE_DEP.DISCOUNT > 0)
                                {
                                    <h3>
                                        <span>@(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE)) VND</span><br />
                                        @(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE * (1 - Model.ElementAt(i).CATE_DEP.DISCOUNT))) VND
                                    </h3>
                                }
                                else
                                {
                                    <h3 style="line-height: 54px">
                                        @(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE)) VND
                                    </h3>
                                }
                            }
                            else
                            {
                                <h3 style="line-height: 54px"> SOLD OUT </h3>
                            }
                            <ul>
                                <li><a class="cart" href='@Url.Action("AddToCart","Checkout", Model.ElementAt(i).ID)' data-pid="@Model.ElementAt(i).ID"> </a></li>
                                <li><a class="i" href="/Product/showProduct?proID=@Model.ElementAt(i).ID"> </a></li>
                            </ul>
                        </div>
                            i++;
                    }
                </div>
            }
            @* Tạo link liên kết các trang*@
            @Html.PagedListPager(Model, page => Url.Action("AdvancedSearch", "Product", new { page = page, name = @ViewBag.name, department = @ViewBag.department, category = @ViewBag.category, MinPrice = @ViewBag.MinPrice, MaxPrice = @ViewBag.MaxPrice }))
            <center>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount</center>
            <div class="clear"></div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"> </div>
</div>

ec-th2012-c/ec-th2012-c/Views/Product/Search.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<ec_th2012_c.Models.PRODUCTS>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="clear"> </div>
<div class="wrap">
    <div class="content">
        @Html.Partial("_Layout_Categories")
        @Html.Partial("_Layout_Search")
        <div class="content-grids">
            @{int size = Model.Count(); int i = 0;}
            @while (i < size)
            {
                <div class="section group">
                    @for (int g = 0; g < 4; g++)
                    {
                        if (i >= size)
                        {
                            break;
                        }
                        <div class="grid_1_of_4 images_1_of_4 products-info">
                            <a href="/Product/showProduct?proID=@Model.ElementAt(i).ID">
                                <img src="@Model.ElementAt(i).IMG" title="@Model.ElementAt(i).NAME">
                            </a>
                            <a href="/Product/showProduct?proID=@Model.ElementAt(i).ID">@Model.ElementAt(i).NAME</a>
                            @if (Model.ElementAt(i).QUANTITY > 0)
                            {
                                if (Model.ElementAt(i).CATE_DEP.DISCOUNT > 0)
                                {
                                    <h3>
                                        <span>@(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE)) VND</span><br />
                                        @(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE * (1 - Model.ElementAt(i).CATE_DEP.DISCOUNT))) VND
                                    </h3>
                                }
                                else
                                {
                                    <h3 style="line-height: 54px">
                                        @(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE)) VND
                                    </h3>
                                }
                            }
                            else
                            {
                                <h3 style="line-height: 54px"> SOLD OUT </h3>
                            }
                            <ul>
                                <li><a class="cart" href='@Url.Action("AddToCart","Checkout", Model.ElementAt(i).ID)' data-pid="@Model.ElementAt(i).ID"> </a></li>
                                <li><a class="i" href="/Product/showProduct?proID=@Model.ElementAt(i).ID"> </a></li>
                            </ul>
                        </div>
                            i++;
                    }
                </div>
            }
            @* Tạo link liên kết các trang*@
            @Html.PagedListPager(Model, page => Url.Action("Error", new { page = page }))
            <center>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount</center>
            <div class="clear"></div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"> </div>
</div>

ec-th2012-c/ec-th2012-c/Views/Product/showCategory.cshtml
@using PagedList.Mvc;
@using PagedList;
@using ec_th2012_c.DAO
@model PagedList.PagedList<ec_th2012_c.Models.PRODUCTS>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="clear"> </div>
<div class="wrap">
    <div class="content">
        @Html.Partial("_Layout_Categories")
        @Html.Partial("_Layout_Search")
        <div class="content-grids">
            <div class="back-links">
                <ul>
                    <li><a href="Index">Home</a><img src="@Url.Content("~/Content/")images/arrow.png" alt=""></li>
                    <li>
                        @Html.ActionLink(new DepartmentDAO().getById(int.Parse(Request["depID"])).NAME, "showCategory", new { depID = Request["depID"] })
                        <img src="@Url.Content("~/Content/")images/arrow.png" alt="">
                    </li>
                </ul>
            </div>

            @{int size = Model.Count(); int i = 0;}
            @while (i < size)
            {
                <div class="section group">
                    @for (int g = 0; g < 4; g++)
                    {
                        if (i >= size)
                        {
                            break;
                        }
                        <div class="grid_1_of_4 images_1_of_4 products-info">
                            <a href="/Product/showProduct?proID=@Model.ElementAt(i).ID">
                                <img src="@Model.ElementAt(i).IMG" title="@Model.ElementAt(i).NAME">
                            </a>
                            <a href="/Product/showProduct?proID=@Model.ElementAt(i).ID">@Model.ElementAt(i).NAME</a>
                            @if (Model.ElementAt(i).QUANTITY > 0)
                            {
                                if (Model.ElementAt(i).CATE_DEP.DISCOUNT > 0)
                                {
                                    <h3>
                                        <span>@(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE)) VND</span><br />
                                        @(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE * (1 - Model.ElementAt(i).CATE_DEP.DISCOUNT))) VND
                                    </h3>
                                }
                                else
                                {
                                    <h3 style="line-height: 54px">
                                        @(string.Format("{0:#,###.##}", Model.ElementAt(i).PRICE)) VND
                                    </h3>
                                }
                            }
                            else
                            {
                                <h3 style="line-height: 54px"> SOLD OUT </h3>
                            }
                            <ul>
                                <li><a class="cart" href='@Url.Action("AddToCart","Checkout", Model.ElementAt(i).ID)' data-pid="@Model.ElementAt(i).ID"> </a></li>
                                <li><a class="i" href="/Product/showProduct?proID=@Model.ElementAt(i).ID"> </a></li>
                            </ul>
                        </div>
                            i++;
                    }
                </div>
            }
            @* Tạo link liên kết các trang*@
            @Html.PagedListPager(Model, page => Url.Action("showCategory", new { depID = ViewBag.depID, cateID = ViewBag.cateID, page = page }))
            <center>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount</center>
            <div class="clear"></div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"> </div>
</div>

ec-th2012-c/ec-th2012-c/Views/Product/showProduct.cshtml
@model ec_th2012_c.Models.PRODUCTS
@using PagedList.Mvc;
@using PagedList;
@using ec_th2012_c.Models
@using Microsoft.AspNet.Identity;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section css
{
    <link rel="stylesheet" href="@Url.Content("~/Content/")css/jqzoom.css" type="text/css">
}
@section scripts
{
    <script src="@Url.Content("~/Content/")js/jqzoom.pack.1.0.1.js" type="text/javascript"></script>
    <script type="text/javascript">
    //function zoom image
        $(function image_zoom() {
            $(".jqzoom").jqzoom();
        });
        //function comment
        $(function comment() {
            $('#submit').on("click", function (event) {
                event.preventDefault();

                var hidend = $('input[name="pID"]').val();
                var message = $('textarea[name="message"]').val();
                
                $.ajax(
                {
                    url: '@Url.Action("Comment", "Product")',
                    type: 'GET',
                    cache: false,
                    datatype: 'json',
                    data: {
                        pID:hidend, message:message
                    }
                }).done(function (data) {
                    var str = "<p>" + data.UserName + ": <span>(" + data.DATECREATE + ")</span><br />" + data.MESSAGE + "</p>";
                    //$.each(data, function(key, value)
                    //{
                    //    str += "<li><p>" + value.AspNetUsers.UserName + ": <span>(" + value.DATACREATE + ")</span><br />" + value.MESSAGE + "</p></li>";
                    //})
                    var newItem = document.createElement("li");
                    var cm = document.getElementById("comments");
                    cm.insertBefore(newItem, cm.childNodes[0]);
                    cm.firstChild.innerHTML = str;
                    $('textarea[name="message"]').val("");
                });
                
            });
        });
    </script>
}


<div class="clear"> </div>
<div class="wrap">
    <div class="content">
        @Html.Partial("_Layout_Categories")
        @Html.Partial("_Layout_Search")
        <div class="content-grids">
            <div class="details-page">
                <div class="back-links">
                    <ul>
                        <li><a href="Index">Home</a><img src="@Url.Content("~/Content/")images/arrow.png" alt=""></li>
                        <li>
                            @Html.ActionLink(Model.CATE_DEP.DEPARTMENTS.NAME, "showCategory", new { depID = Model.CATE_DEP.DEPARTMENT_ID })
                            <img src="@Url.Content("~/Content/")images/arrow.png" alt="">
                        </li>
                        <li>
                            @Html.ActionLink(Model.CATE_DEP.CATELOGIES.NAME, "showCategory", new { depID = Model.CATE_DEP.DEPARTMENT_ID, cateID = Model.CATE_DEP.CATEGORY_ID })
                            <img src="@Url.Content("~/Content/")images/arrow.png" alt="">
                        </li>
                    </ul>
                </div>
            </div>
            <div class="clear"> </div>
            <div class="details-image">
                <div id="content">
                    <a href="@Model.IMG" class="jqzoom" style="" title="@Model.NAME"> <img src="@Model.IMG" title="@Model.NAME" style="border: 1px solid #e5e5e5;"> </a>
                </div>
                <div class="share">
                    <ul>
                        <li> <a href="https://wwww.facebook.com/" target="_blank"><img src="@Url.Content("~/Content/")images/facebook.png" title="Facebook" /> Fb</a></li>
                        <li> <a href="https://wwww.twitter.com" target="_blank"><img src="@Url.Content("~/Content/")images/twitter.png" title="Twitter" />Tw</a></li>
                        <li> <a href="#"><img src="@Url.Content("~/Content/")images/rss.png" title="Rss" />Rss</a></li>
                    </ul>
                </div>
            </div>
            <div class="details-image-details">
                <div class="details-categories">
                    <ul>
                        <li><h3>Category:</h3></li>
                        @foreach (CATELOGIES _c in (IList<CATELOGIES>)ViewBag.categories)
                        {
                            if (_c.ID.Equals(Model.CATE_DEP.CATEGORY_ID))
                            {
                                <li class="active1"><a href="/Home/showCategory?depID=@Model.CATE_DEP.DEPARTMENT_ID&cateID=@_c.ID"><span>@_c.NAME</span></a></li>
                            }
                            else
                            {
                                <li><a href="/Home/showCategory?depID=@Model.CATE_DEP.DEPARTMENT_ID&cateID=@_c.ID">@_c.NAME</a></li>
                            }
                        }
                    </ul>
                </div>
                <br /><br /><div class="clear"></div>
                <div class="brand-value">
                    <h3>@Model.NAME</h3>
                    <div class="left-value-details">
                        <ul>
                            <li>Price:</li>
                            @if (@Model.CATE_DEP.DISCOUNT > 0)
                            {
                                <li><span>@(string.Format("{0:#,###.##}", Model.PRICE)) VND</span></li>
                                <br />
                                <li><h5>@(string.Format("{0:#,###.##}", Model.PRICE * (1 - @Model.CATE_DEP.DISCOUNT))) VND</h5></li>
                                <br />
                                <li><p>DISCOUNT: @(Model.CATE_DEP.DISCOUNT * 100)%</p></li>
                            }
                            else
                            {
                                <br />
                                <li><h5>@(string.Format("{0:#,###.##}", Model.PRICE)) VND</h5></li>
                            }
                        </ul>
                    </div>
                    <div class="right-value-details">
                        @if (Model.QUANTITY > 0)
                        {
                            <p>IN STOCK</p>
                        }
                        else
                        {
                            <h6>SOLD OUT</h6>
                        }
                        <a href="#reviews">@Model.COMMENT.Count() reviews</a>
                    </div>
                    <div class="clear"> </div>
                </div>
                <br /><br /><div class="clear"></div>
                <div class="brand-history">
                    <h3>Description :</h3>
                    <p>@Model.DESCRIPTION</p>
                    <a class="cart" href='@Url.Action("AddToCart","Checkout", Model.ID)' data-pid="@Model.ID">Addcart</a>
                </div>
                <div class="clear"> </div>
            </div>
            <div class="clear"> </div>
            <div class="menu_container">
                <div class="menu_head">Product Details<span class="plusminus">-</span></div>
                <div class="menu_body" style="display: none;">
                    <div class="details-product">
                        <table title="PRODUCT DETAILS">
                            @foreach (PRODUCT_INFO i in Model.PRODUCT_INFO)
                            {
                                <tr>
                                    <td>@i.INFO.NAME</td>
                                    <td>@i.VALUE</td>
                                </tr>
                            }
                        </table>
                        <p></p>
                    </div>
                </div>
                <div class="menu_head" id="reviews">Reviews<span class="plusminus">-</span></div>
                <div class="menu_body" style="display: none;">
                    <ul>
                        <li>
                            @if (User.Identity.GetUserId() == null)
                            {
                                <a class="btn btn-primary" href="@Url.Action("Login","Account")">Login to comment </a>
                            }
                            else
                            {
                                using (Html.BeginForm("Comment", "Product", FormMethod.Get, new { id = "frmCmt" }))
                                {
                                    <input type="hidden" name="pID" value="@Model.ID" />
                                    <textarea name="message" rows="4"></textarea>
                                    @*<input type="text" name="message" />*@
                                    <input type="submit" value="Comment" id="submit"/>
                                }
                            }
                        </li>
                    </ul>
                    <ul id="comments">
                        @foreach (COMMENT cm in Model.COMMENT.OrderByDescending(c => c.DATACREATE))
                        {
                            <li><p>@cm.AspNetUsers.UserName: <span>(@cm.DATACREATE)</span><br />@cm.MESSAGE</p></li>
                        }
                    </ul>
                    <p></p>
                </div>
            </div>
            <div class="clear"> </div>
            <br />
            <div class="container">
                <div class="menu_head">Offer Products</div>
                <div class="container">
                    @{ int j = 0; var SameCategoryItemList = (ViewBag.SameCategoryItems as PagedList<PRODUCTS>); int size = SameCategoryItemList.Count();
                     while (j < size)
                     {
                        <div class="section group">
                            @for (int g = 0; g < 4; g++)
                            {
                                if (j >= size)
                                {
                                    break;
                                }
                                <div class="grid_1_of_4 images_1_of_4 products-info">
                                    <a href="/Product/showProduct?proID=@SameCategoryItemList.ElementAt(j).ID">
                                        <img src="@SameCategoryItemList.ElementAt(j).IMG" title="@SameCategoryItemList.ElementAt(j).NAME">
                                    </a>
                                    <a href="/Product/showProduct?proID=@SameCategoryItemList.ElementAt(j).ID">@SameCategoryItemList.ElementAt(j).NAME</a>
                                    @if (SameCategoryItemList.ElementAt(j).QUANTITY > 0)
                                    {
                                        if (SameCategoryItemList.ElementAt(j).CATE_DEP.DISCOUNT > 0)
                                        {
                                            <h3>
                                                <span>@(string.Format("{0:#,###.##}", SameCategoryItemList.ElementAt(j).PRICE)) VND</span><br />
                                                @(string.Format("{0:#,###.##}", SameCategoryItemList.ElementAt(j).PRICE * (1 - SameCategoryItemList.ElementAt(j).CATE_DEP.DISCOUNT))) VND
                                            </h3>
                                        }
                                        else
                                        {
                                            <h3 style="line-height: 54px">
                                                @(string.Format("{0:#,###.##}", SameCategoryItemList.ElementAt(j).PRICE)) VND
                                            </h3>
                                        }
                                    }
                                    else
                                    {
                                        <h3 style="line-height: 54px"> SOLD OUT </h3>
                                    }
                                    <ul>
                                        <li><a class="cart" href='@Url.Action("AddToCart", "Checkout", SameCategoryItemList.ElementAt(j).ID)' data-pid="@SameCategoryItemList.ElementAt(j).ID"> </a></li>
                                        <li><a class="i" href="/Product/showProduct?proID=@SameCategoryItemList.ElementAt(j).ID"> </a></li>
                                    </ul>
                                </div>
                                    j++;
                            }
                        </div>
                     }
                    }

                    @* Tạo link liên kết các trang*@


                    @if (SameCategoryItemList.Count != 0)
                    {
                        @Html.PagedListPager(SameCategoryItemList, page => Url.Action("showProduct", new { proID = ViewBag.proID, page = page }))
                        <center>Page @(SameCategoryItemList.PageCount < SameCategoryItemList.PageNumber ? 0 : SameCategoryItemList.PageNumber) / @SameCategoryItemList.PageCount</center>
                        <div class="clear"></div>

                    }
                    else
                    {
                        <h1>No product to offer</h1>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clear"> </div>